/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package breakIterator;

import java.text.BreakIterator;
import java.util.Locale;

public class Library {
   public static void main(String[] args) {
	   Locale locale = Locale.UK;
	   BreakIterator breakIterator =
	           BreakIterator.getWordInstance(locale);

	   breakIterator.setText("Mary had a little Android device 1.");

	   int firstIndex = breakIterator.first();
	   while(firstIndex != BreakIterator.DONE) {
		   int lastIndex = breakIterator.next();
		   if(lastIndex != BreakIterator.DONE)
			  if(!"Mary had a little Android device 1.".substring(firstIndex, lastIndex).matches(".*\\d.*"))
	       System.out.println("Mary had a little Android device 1.".substring(firstIndex, lastIndex)) ;
	       firstIndex = lastIndex;
	   }
   }
}
